<?xml version="1.0" encoding="UTF-8"?>
<testExecutions version="1">
  <file path="/Users/lenny/Projects/hello-next/src/__tests__/Footer.test.js">
    <testCase name="Footer Component should have the copyright in the footer" duration="26"/>
  </file>
  <file path="/Users/lenny/Projects/hello-next/src/__tests__/Header.test.js">
    <testCase name="Header renders Header component with the example nav passed" duration="40"/>
  </file>
  <file path="/Users/lenny/Projects/hello-next/src/__tests__/Layout.test.js">
    <testCase name="Layout toggles the navigation" duration="185"/>
  </file>
  <file path="/Users/lenny/Projects/hello-next/src/__tests__/example.test.js">
    <testCase name="sum function should add two numbers together" duration="3"/>
    <testCase name="testing with jest matchers object assignment" duration="1"/>
    <testCase name="testing with jest matchers adding positive numbers is not zero" duration="25"/>
    <testCase name="testing with jest truthiness null" duration="1"/>
    <testCase name="testing with jest truthiness zero" duration="0"/>
    <testCase name="testing with jest numbers two plus two" duration="1"/>
    <testCase name="testing with jest numbers adding floating point numbers" duration="1"/>
    <testCase name="testing with jest strings there is no I in team" duration="0"/>
    <testCase name="testing with jest strings but there is a &quot;stop&quot; in Christoph" duration="0"/>
    <testCase name="testing with jest arrays and iterables the shopping list has beer on it" duration="0"/>
    <testCase name="testing with jest exceptions compiling android goes as expected" duration="6"/>
    <testCase name="testing with jest callbacks the data is peanut butter" duration="101"/>
    <testCase name="testing with jest promises/resolve/reject/catch/async/await the data is peanut butter, then" duration="100"/>
    <testCase name="testing with jest promises/resolve/reject/catch/async/await the fetch fails with an error, catch" duration="101"/>
    <testCase name="testing with jest promises/resolve/reject/catch/async/await the data is peanut butter, resolves" duration="101"/>
    <testCase name="testing with jest promises/resolve/reject/catch/async/await the fetch fails with an error, rejects" duration="103"/>
    <testCase name="testing with jest promises/resolve/reject/catch/async/await the data is peanut butter" duration="103"/>
    <testCase name="testing with jest promises/resolve/reject/catch/async/await the fetch fails with an error" duration="101"/>
    <testCase name="testing with jest promises/resolve/reject/catch/async/await the data is peanut butter" duration="104"/>
    <testCase name="testing with jest promises/resolve/reject/catch/async/await the fetch fails with an error" duration="102"/>
    <testCase name="testing with jest should check truth" duration="0"/>
  </file>
</testExecutions>